### PR TITLE
popstate bug fix

### PR DESCRIPTION
**Pull request by albertopfunk**
- uri == null when user 'popstates' back to first home page hx
- breaks .split()
- quick fix with uri && ...

Hello :D 
hoping to make my first ever open source contribution!
Also wanted to say thanks for this demo, made using navaid with svelte much more approachable

### CODE REVIEW

**Comment by lukeed** [comment]
Hey,

Awesome, thanks & good catch!

I was confused and did some digging, since I know that `location.pathname` is _always_ `/` at minimum. This actually exposed another problem too and I think you're better off fixing both here. 

Since `location.pathname` can't be causing the error, then it had to be the `track()` function, because it's the only other place that `uri` is assigned. On that `popstate` event, it's getting `null` and so that's why the error splits. This also means that in production (when `window.ga` is defined) it'd be sending an invalid `dp` value.

Instead of what you have (which does work, 🙏 thanks!) let's change line 30 so that the full function looks like this:

```js
	function track(obj) {
		uri = obj.state || obj.uri || location.pathname;
		if (window.ga) ga.send('pageview', { dp:uri });
	}
```

This falls back to the current location, which is what it should be doing.

Thanks again!

**Comment by albertopfunk** [comment]
Ah yes that's what was confusing me too!
I have like a week of experience with svelte, so I thought it might have possibly been like a re-render, but then I saw that the App never unmounts, so it was throwing me off hehe
Would you mind explaining that line by the way? 'if (window.ga) ga.send('pageview', { dp:uri });'
so far this is the only part I was not able to understand

**Comment by lukeed** [comment]
Ah, looks like I removed the ganalytics integration from an earlier version of this template. Oops! Will immediately push up the missing piece, but the idea is that for production builds only, a [`ganalytics`](https://github.com/lukeed/ganalytics) instance is created for lightweight Google Analytics integration. I usually have this snippet in place for any Navaid demo.

**Comment by lukeed** [comment]
Thanks again!

**Comment by albertopfunk** [comment]
Gotcha! No worries it was a great learning experience, thank you for taking the time as well :D

**Comment by lukeed** [comment]
You bet. I pushed the missing bits to the repo already, too.

**Pull request merged**
